//! Agent TLS termination.
//!
//! `pier-agent` serves its API over HTTPS with a self-signed certificate.
//! There is no CA to chain to — core reaches the agent by raw IP or by its
//! WireGuard mesh IP, neither of which a public CA certifies. Instead core
//! **pins this cert's SHA-256 leaf fingerprint** (delivered during the
//! install-script handshake). This module loads the cert/key (generated by
//! the installer via openssl, or here as a fallback) and computes the
//! fingerprint core will pin.
//!
//! The fingerprint is the SHA-256 of the DER-encoded leaf certificate,
//! lowercase hex — byte-for-byte what `openssl x509 -outform DER | sha256sum`
//! and `pier-core`'s verifier produce.

use std::path::Path;

use anyhow::{anyhow, Context, Result};
use axum_server::tls_rustls::RustlsConfig;
use rcgen::{generate_simple_self_signed, CertifiedKey};
use sha2::{Digest, Sha256};

const CERT_FILE: &str = "cert.pem";
const KEY_FILE: &str = "key.pem";

/// Loaded agent TLS material plus the leaf fingerprint core pins.
pub struct AgentTls {
    pub config: RustlsConfig,
    /// Lowercase-hex SHA-256 of the leaf certificate DER.
    pub fingerprint: String,
}

/// Load the agent cert/key from `dir`, generating a self-signed pair on first
/// run if absent. Returns the rustls config and the leaf fingerprint.
pub async fn load_or_generate(dir: &Path) -> Result<AgentTls> {
    let cert_path = dir.join(CERT_FILE);
    let key_path = dir.join(KEY_FILE);

    if !cert_path.exists() || !key_path.exists() {
        std::fs::create_dir_all(dir)
            .with_context(|| format!("create agent TLS dir {}", dir.display()))?;
        generate_self_signed(&cert_path, &key_path).context("generate self-signed agent cert")?;
        tracing::info!(
            "Generated self-signed agent TLS cert at {}",
            cert_path.display()
        );
    }

    let fingerprint = leaf_fingerprint(&cert_path)
        .with_context(|| format!("fingerprint {}", cert_path.display()))?;

    let config = RustlsConfig::from_pem_file(&cert_path, &key_path)
        .await
        .with_context(|| {
            format!(
                "load agent TLS material from {} / {}",
                cert_path.display(),
                key_path.display()
            )
        })?;

    Ok(AgentTls {
        config,
        fingerprint,
    })
}

/// SHA-256 of the first (leaf) certificate's DER, lowercase hex.
fn leaf_fingerprint(cert_path: &Path) -> Result<String> {
    let pem = std::fs::read(cert_path).with_context(|| format!("read {}", cert_path.display()))?;
    let mut reader = std::io::BufReader::new(&pem[..]);
    let certs = rustls_pemfile::certs(&mut reader)
        .collect::<std::result::Result<Vec<_>, _>>()
        .with_context(|| format!("parse certs in {}", cert_path.display()))?;
    let leaf = certs
        .first()
        .ok_or_else(|| anyhow!("no certificate in {}", cert_path.display()))?;
    Ok(hex::encode(Sha256::digest(leaf.as_ref())))
}

fn generate_self_signed(cert_path: &Path, key_path: &Path) -> Result<()> {
    // SANs are cosmetic here — core's verifier ignores hostname and checks
    // only the fingerprint — but a couple of sensible entries keep the cert
    // usable with ordinary tooling (`openssl s_client`, `curl -k`).
    let sans = vec![
        "localhost".to_string(),
        "127.0.0.1".to_string(),
        "::1".to_string(),
    ];
    let CertifiedKey { cert, signing_key } = generate_simple_self_signed(sans)?;
    write_secret(key_path, signing_key.serialize_pem().as_bytes())?;
    std::fs::write(cert_path, cert.pem())
        .with_context(|| format!("write {}", cert_path.display()))?;
    Ok(())
}

#[cfg(unix)]
fn write_secret(path: &Path, bytes: &[u8]) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
        .with_context(|| format!("open {} for write", path.display()))?;
    f.write_all(bytes)
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn write_secret(path: &Path, bytes: &[u8]) -> Result<()> {
    std::fs::write(path, bytes).with_context(|| format!("write {}", path.display()))
}
