use std::path::Path;

use anyhow::Result;

/// Generate Traefik static configuration (traefik.yml).
pub fn generate_static_config(acme_email: &str, dashboard: bool) -> String {
    let dashboard_section = if dashboard {
        "api:\n  dashboard: true\n  insecure: true"
    } else {
        "api:\n  dashboard: false"
    };

    format!(
        r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
    )
}

/// Generate Traefik dynamic config for a single domain → service mapping.
///
/// `service_id`: unique key for the router/service name
/// `domain`: the FQDN to route (e.g. "app.example.com")
/// `target_url`: upstream URL (e.g. "http://127.0.0.1:10042")
/// `use_tls`: whether to enable Let's Encrypt TLS
#[allow(dead_code)]
pub fn generate_dynamic_config(
    service_id: &str,
    domain: &str,
    target_url: &str,
    use_tls: bool,
) -> String {
    let tls_section = if use_tls {
        r#"      tls:
        certResolver: letsencrypt"#
            .to_string()
    } else {
        String::new()
    };

    // Parse domain: may contain path prefix (e.g., "example.com/v1")
    let (hostname, path_prefix) = if let Some(slash) = domain.find('/') {
        (&domain[..slash], Some(&domain[slash..]))
    } else {
        (domain, None)
    };
    let (rule, middleware_section, middleware_ref) = if let Some(path) = path_prefix {
        let mw_name = format!("strip-pier-{service_id}");
        (
            format!("Host(`{hostname}`) && PathPrefix(`{path}`)"),
            format!(
                r#"  middlewares:
    {mw_name}:
      stripPrefix:
        prefixes:
          - "{path}"
"#
            ),
            format!("\n      middlewares:\n        - {mw_name}"),
        )
    } else {
        (format!("Host(`{hostname}`)"), String::new(), String::new())
    };

    format!(
        r#"# Auto-generated by Pier for service {service_id}
http:
  routers:
    pier-{service_id}:
      rule: "{rule}"
      entryPoints:
        - websecure
{tls_section}{middleware_ref}
      service: pier-{service_id}
{middleware_section}  services:
    pier-{service_id}:
      loadBalancer:
        servers:
          - url: "{target_url}"
"#
    )
}

/// Write the Traefik static config to disk.
pub fn write_static_config(data_dir: &Path, acme_email: &str, dashboard: bool) -> Result<()> {
    let traefik_dir = data_dir.join("traefik");
    std::fs::create_dir_all(&traefik_dir)?;
    std::fs::create_dir_all(traefik_dir.join("dynamic"))?;

    // Preserve existing TCP entryPoints from current config
    let existing_tcp_ports = read_tcp_ports_from_config(data_dir);
    let config = if existing_tcp_ports.is_empty() {
        generate_static_config(acme_email, dashboard)
    } else {
        // Use regenerate_static_config_with_tcp to keep TCP ports
        let mut tcp_entries = String::new();
        for port in &existing_tcp_ports {
            tcp_entries.push_str(&format!("  tcp-{port}:\n    address: \":{port}\"\n"));
        }
        let dashboard_section = if dashboard {
            "api:\n  dashboard: true\n  insecure: true"
        } else {
            "api:\n  dashboard: false"
        };
        let cfg = format!(
            r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
{tcp_entries}
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
        );
        cfg
    };
    std::fs::write(traefik_dir.join("traefik.yml"), config)?;

    // Ensure acme.json exists with correct permissions (600 required by Traefik)
    let acme_path = traefik_dir.join("acme.json");
    if !acme_path.exists() {
        std::fs::write(&acme_path, "{}")?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&acme_path, std::fs::Permissions::from_mode(0o600))?;
    }

    Ok(())
}

/// Write a dynamic config file for a domain.
#[allow(dead_code)]
pub fn write_domain_config(
    data_dir: &Path,
    service_id: &str,
    domain: &str,
    target_url: &str,
    use_tls: bool,
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let config = generate_dynamic_config(service_id, domain, target_url, use_tls);
    let file_name = format!("{service_id}.yml");
    std::fs::write(dynamic_dir.join(file_name), config)?;

    Ok(())
}

/// Remove a dynamic config file for a service.
#[allow(dead_code)]
pub fn remove_domain_config(data_dir: &Path, service_id: &str) -> Result<()> {
    let file_path = data_dir
        .join("traefik")
        .join("dynamic")
        .join(format!("{service_id}.yml"));
    if file_path.exists() {
        std::fs::remove_file(file_path)?;
    }
    Ok(())
}

/// Generate a service domain using sslip.io (like Coolify).
/// Format: {name}-{short_id}.{ip}.sslip.io
pub fn generate_service_domain(service_name: &str, service_id: &str, server_ip: &str) -> String {
    // Clean name: lowercase, replace non-alphanumeric with dash
    let clean_name: String = service_name
        .to_lowercase()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    let clean_name = clean_name.trim_matches('-');

    // Take first 8 chars of service_id for short id
    let short_id = &service_id[..service_id.len().min(8)];

    format!("{clean_name}-{short_id}.{server_ip}.sslip.io")
}

/// One upstream endpoint behind the Traefik load balancer.
#[derive(Debug, Clone)]
pub struct LbUpstream {
    pub url: String,
    /// Relative weight. Only emitted when strategy == `Weighted`.
    pub weight: u32,
}

/// L7 load-balancing strategy for a service's upstreams.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LbStrategy {
    RoundRobin,
    Weighted,
    Sticky,
}

/// Extra load-balancer knobs (strategy + sticky cookie).
#[derive(Debug, Clone)]
pub struct LbConfig {
    pub strategy: LbStrategy,
    /// Cookie name used when `strategy == Sticky`. Ignored otherwise.
    pub sticky_cookie: Option<String>,
}

impl Default for LbConfig {
    fn default() -> Self {
        Self {
            strategy: LbStrategy::RoundRobin,
            sticky_cookie: None,
        }
    }
}

/// Generate Traefik dynamic config for a service with multiple domains and
/// multiple upstreams (replicas). When `upstreams.len() == 1` and strategy is
/// `RoundRobin`, the output matches legacy single-upstream YAML byte-for-byte.
pub fn generate_dynamic_config_lb(
    service_id: &str,
    domains: &[(String, bool)],
    upstreams: &[LbUpstream],
    lb: &LbConfig,
) -> String {
    let mut routers = String::new();
    let mut middlewares = String::new();
    for (i, (domain_with_path, use_tls)) in domains.iter().enumerate() {
        let router_name = if i == 0 {
            format!("pier-{service_id}")
        } else {
            format!("pier-{service_id}-{i}")
        };
        let tls_section = if *use_tls {
            "\n      tls:\n        certResolver: letsencrypt".to_string()
        } else {
            String::new()
        };
        let (hostname, path_prefix) = if let Some(slash) = domain_with_path.find('/') {
            (&domain_with_path[..slash], Some(&domain_with_path[slash..]))
        } else {
            (domain_with_path.as_str(), None)
        };
        let (rule, middleware_ref) = if let Some(path) = path_prefix {
            let mw_name = format!("strip-{router_name}");
            middlewares.push_str(&format!(
                r#"    {mw_name}:
      stripPrefix:
        prefixes:
          - "{path}"
"#
            ));
            (
                format!("Host(`{hostname}`) && PathPrefix(`{path}`)"),
                format!("\n      middlewares:\n        - {mw_name}"),
            )
        } else {
            (format!("Host(`{hostname}`)"), String::new())
        };
        routers.push_str(&format!(
            r#"    {router_name}:
      rule: "{rule}"
      entryPoints:
        - websecure{tls_section}{middleware_ref}
      service: pier-{service_id}
"#
        ));
    }

    let mw_section = if middlewares.is_empty() {
        String::new()
    } else {
        format!("  middlewares:\n{middlewares}")
    };

    let sticky_section = match (&lb.strategy, &lb.sticky_cookie) {
        (LbStrategy::Sticky, Some(cookie)) => format!(
            r#"        sticky:
          cookie:
            name: {cookie}
            httpOnly: true
            secure: true
"#
        ),
        _ => String::new(),
    };

    let include_weight = lb.strategy == LbStrategy::Weighted;
    let mut servers_yaml = String::new();
    for up in upstreams {
        if include_weight {
            servers_yaml.push_str(&format!(
                "          - url: \"{}\"\n            weight: {}\n",
                up.url, up.weight
            ));
        } else {
            servers_yaml.push_str(&format!("          - url: \"{}\"\n", up.url));
        }
    }

    format!(
        r#"# Auto-generated by Pier for service {service_id}
http:
  routers:
{routers}{mw_section}  services:
    pier-{service_id}:
      loadBalancer:
{sticky_section}        servers:
{servers_yaml}"#
    )
}

/// Legacy wrapper — single upstream, round-robin, no sticky.
#[allow(dead_code)]
pub fn generate_dynamic_config_multi(
    service_id: &str,
    domains: &[(String, bool)],
    target_url: &str,
) -> String {
    generate_dynamic_config_lb(
        service_id,
        domains,
        &[LbUpstream {
            url: target_url.to_string(),
            weight: 1,
        }],
        &LbConfig::default(),
    )
}

/// One row in the multi-target dynamic config: a domain that should route
/// to a specific upstream URL, optionally tagged with the compose-service
/// it represents (used to group routers + Traefik service blocks).
#[derive(Debug, Clone)]
pub struct DomainTarget {
    pub domain: String,
    pub use_tls: bool,
    /// `Some("svc")` for multi-service composes, `None` for single-target services.
    pub compose_service: Option<String>,
    /// Full upstream URL, e.g. `http://api:3000`.
    pub target_url: String,
}

/// Generate a Traefik dynamic config that supports multiple HTTP routers
/// fanning out to different upstream services. Used when one Pier resource
/// (one compose file) hosts several containers that each need their own
/// domain (e.g. `tma.x → telegram-bot:3000` + `max.x → max-bot:3000`).
///
/// Routers are grouped by `compose_service` (None = single shared service).
/// Within a group every domain points at the same Traefik service block.
fn generate_dynamic_config_multi_target(service_id: &str, targets: &[DomainTarget]) -> String {
    use std::collections::BTreeMap;

    // Stable group key: None comes first, then sorted compose_service names.
    let mut groups: BTreeMap<String, Vec<&DomainTarget>> = BTreeMap::new();
    for t in targets {
        let key = t.compose_service.clone().unwrap_or_default();
        groups.entry(key).or_default().push(t);
    }

    let mut routers = String::new();
    let mut middlewares = String::new();
    let mut services_yaml = String::new();
    let mut router_idx = 0usize;
    for (group_key, group) in &groups {
        let svc_suffix = if group_key.is_empty() {
            String::new()
        } else {
            format!("-{}", sanitize_traefik_name(group_key))
        };
        let svc_name = format!("pier-{service_id}{svc_suffix}");
        // Upstream URL is identical within a compose-service group; take the first.
        let upstream = group
            .first()
            .map(|t| t.target_url.as_str())
            .unwrap_or_default();
        services_yaml.push_str(&format!(
            r#"    {svc_name}:
      loadBalancer:
        servers:
          - url: "{upstream}"
"#
        ));

        for t in group {
            let router_name = if router_idx == 0 {
                format!("pier-{service_id}{svc_suffix}")
            } else {
                format!("pier-{service_id}{svc_suffix}-{router_idx}")
            };
            router_idx += 1;
            let tls_section = if t.use_tls {
                "\n      tls:\n        certResolver: letsencrypt".to_string()
            } else {
                String::new()
            };
            let (hostname, path_prefix) = if let Some(slash) = t.domain.find('/') {
                (&t.domain[..slash], Some(&t.domain[slash..]))
            } else {
                (t.domain.as_str(), None)
            };
            let (rule, middleware_ref) = if let Some(path) = path_prefix {
                let mw_name = format!("strip-{router_name}");
                middlewares.push_str(&format!(
                    "    {mw_name}:\n      stripPrefix:\n        prefixes:\n          - \"{path}\"\n"
                ));
                (
                    format!("Host(`{hostname}`) && PathPrefix(`{path}`)"),
                    format!("\n      middlewares:\n        - {mw_name}"),
                )
            } else {
                (format!("Host(`{hostname}`)"), String::new())
            };
            routers.push_str(&format!(
                r#"    {router_name}:
      rule: "{rule}"
      entryPoints:
        - websecure{tls_section}{middleware_ref}
      service: {svc_name}
"#
            ));
        }
    }

    let mw_section = if middlewares.is_empty() {
        String::new()
    } else {
        format!("  middlewares:\n{middlewares}")
    };

    format!(
        r#"# Auto-generated by Pier for service {service_id}
http:
  routers:
{routers}{mw_section}  services:
{services_yaml}"#
    )
}

/// Sanitize a compose-service name for use in Traefik router/service IDs.
/// Traefik tolerates most characters but we restrict to `[A-Za-z0-9_-]`
/// to be safe. Replaces anything else with `-`.
fn sanitize_traefik_name(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

/// Regenerate the Traefik dynamic config from a list of (domain → target_url)
/// pairs grouped by compose-service. This is the multi-target variant used
/// when one Pier resource contains multiple containers each needing their
/// own domain. For single-target services callers can keep using
/// `regenerate_service_config` (it's a one-target wrapper that delegates here).
pub fn regenerate_service_config_multi(
    data_dir: &Path,
    service_id: &str,
    targets: &[DomainTarget],
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;
    let file_path = dynamic_dir.join(format!("{service_id}.yml"));

    if targets.is_empty() {
        if file_path.exists() {
            std::fs::remove_file(file_path)?;
        }
        return Ok(());
    }

    let config = generate_dynamic_config_multi_target(service_id, targets);
    if let Ok(existing) = std::fs::read_to_string(&file_path) {
        if existing == config {
            return Ok(());
        }
    }
    std::fs::write(file_path, config)?;
    Ok(())
}

/// Regenerate Traefik config for a service with ALL its domains.
/// If no domains remain, removes the config file.
pub fn regenerate_service_config(
    data_dir: &Path,
    service_id: &str,
    domains: &[(String, bool)],
    target_url: &str,
) -> Result<()> {
    regenerate_service_config_lb(
        data_dir,
        service_id,
        domains,
        &[LbUpstream {
            url: target_url.to_string(),
            weight: 1,
        }],
        &LbConfig::default(),
    )
}

/// Regenerate Traefik config with an arbitrary upstream list + LB config.
pub fn regenerate_service_config_lb(
    data_dir: &Path,
    service_id: &str,
    domains: &[(String, bool)],
    upstreams: &[LbUpstream],
    lb: &LbConfig,
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;
    let file_path = dynamic_dir.join(format!("{service_id}.yml"));

    if domains.is_empty() || upstreams.is_empty() {
        if file_path.exists() {
            std::fs::remove_file(file_path)?;
        }
        return Ok(());
    }

    let config = generate_dynamic_config_lb(service_id, domains, upstreams, lb);
    if let Ok(existing) = std::fs::read_to_string(&file_path) {
        if existing == config {
            return Ok(());
        }
    }
    std::fs::write(file_path, config)?;
    Ok(())
}

/// Write Traefik config for the Pier platform domain.
pub fn write_platform_domain_config(data_dir: &Path, domain: &str, target_url: &str) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let config = format!(
        r#"# Pier platform domain
http:
  routers:
    pier-platform:
      rule: "Host(`{domain}`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: pier-platform
  services:
    pier-platform:
      loadBalancer:
        servers:
          - url: "{target_url}"
"#
    );
    std::fs::write(dynamic_dir.join("_pier-platform.yml"), config)?;
    Ok(())
}

/// Remove the platform domain config.
pub fn remove_platform_domain_config(data_dir: &Path) -> Result<()> {
    let path = data_dir
        .join("traefik")
        .join("dynamic")
        .join("_pier-platform.yml");
    if path.exists() {
        std::fs::remove_file(path)?;
    }
    Ok(())
}

/// Check whether the platform domain dynamic config exists on disk and embeds
/// `expected_domain`. Used by the UI to surface "configured & loaded" state.
pub fn platform_domain_router_present(data_dir: &Path, expected_domain: &str) -> bool {
    let path = data_dir
        .join("traefik")
        .join("dynamic")
        .join("_pier-platform.yml");
    let Ok(contents) = std::fs::read_to_string(&path) else {
        return false;
    };
    contents.contains(&format!("Host(`{expected_domain}`)"))
}

/// Normalize a user-entered domain: strip scheme, userinfo, path, port, trailing dot, lowercase.
/// Returns empty string if nothing usable remains.
///
/// Traefik `Host()` matchers require a bare hostname; pasting a full URL like
/// `https://pier.example.com/` produces an invalid rule that silently fails to match.
pub fn normalize_domain(input: &str) -> String {
    let s = input.trim();
    if s.is_empty() {
        return String::new();
    }
    let s = s.split_once("://").map(|(_, rest)| rest).unwrap_or(s);
    let s = s.split(['/', '?', '#']).next().unwrap_or(s);
    let s = s.rsplit_once('@').map(|(_, rest)| rest).unwrap_or(s);
    let s = s.split_once(':').map(|(host, _)| host).unwrap_or(s);
    s.trim_end_matches('.').to_ascii_lowercase()
}

#[cfg(test)]
mod normalize_domain_tests {
    use super::normalize_domain;

    #[test]
    fn strips_scheme_path_port_and_lowercases() {
        assert_eq!(normalize_domain(""), "");
        assert_eq!(normalize_domain("   "), "");
        assert_eq!(normalize_domain("pier.example.com"), "pier.example.com");
        assert_eq!(normalize_domain("https://pier.example.com"), "pier.example.com");
        assert_eq!(normalize_domain("https://pier.example.com/"), "pier.example.com");
        assert_eq!(
            normalize_domain("http://user:pass@pier.example.com:8080/path?q=1#x"),
            "pier.example.com"
        );
        assert_eq!(normalize_domain("PIER.EXAMPLE.COM."), "pier.example.com");
    }
}

/// Write a Traefik TCP dynamic config for exposing a service port publicly.
/// Each upstream is a raw `host:port` string (can be a Docker DNS name
/// for local replicas or `ip:port` for remote replicas). Traefik's TCP
/// provider distributes connections across all listed upstreams (WRR).
///
/// File name is `tcp-{service_id}-{public_port}.yml` so a single service can
/// expose multiple raw TCP ports simultaneously (e.g. REST 4471 + MQTT 1883).
/// Router/service names inside the YAML include the port for the same reason.
pub fn write_tcp_route_lb(
    data_dir: &Path,
    service_id: &str,
    public_port: u16,
    upstreams: &[String],
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let ep_name = format!("tcp-{public_port}");
    let route_name = format!("tcp-{service_id}-{public_port}");
    let servers_yaml: String = upstreams
        .iter()
        .map(|addr| format!("          - address: \"{addr}\"\n"))
        .collect();
    let config = format!(
        r#"# TCP proxy for service {service_id} (public :{public_port} -> {} upstream(s))
tcp:
  routers:
    {route_name}:
      entryPoints:
        - "{ep_name}"
      rule: "HostSNI(`*`)"
      service: "{route_name}"
  services:
    {route_name}:
      loadBalancer:
        servers:
{servers_yaml}"#,
        upstreams.len()
    );

    std::fs::write(dynamic_dir.join(format!("{route_name}.yml")), config)?;
    Ok(())
}

/// Legacy single-upstream wrapper kept for callers that still deal with
/// one container.
#[allow(dead_code)]
pub fn write_tcp_route(
    data_dir: &Path,
    service_id: &str,
    public_port: u16,
    container_name: &str,
    container_port: u16,
) -> Result<()> {
    write_tcp_route_lb(
        data_dir,
        service_id,
        public_port,
        &[format!("{container_name}:{container_port}")],
    )
}

/// Remove all TCP route configs for a service: both the legacy
/// `tcp-{service_id}.yml` (single-port era) and the per-port files
/// `tcp-{service_id}-{port}.yml`.
pub fn remove_tcp_route(data_dir: &Path, service_id: &str) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    // Legacy single-port file
    let legacy = dynamic_dir.join(format!("tcp-{service_id}.yml"));
    if legacy.exists() {
        let _ = std::fs::remove_file(&legacy);
    }
    // Per-port files: tcp-{service_id}-{port}.yml
    let prefix = format!("tcp-{service_id}-");
    if let Ok(entries) = std::fs::read_dir(&dynamic_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with(&prefix) && name_str.ends_with(".yml") {
                let _ = std::fs::remove_file(entry.path());
            }
        }
    }
    Ok(())
}

/// Remove the TCP route file for a single (service, port) pair, leaving
/// other ports of the same service untouched.
#[allow(dead_code)]
pub fn remove_tcp_route_for_port(
    data_dir: &Path,
    service_id: &str,
    public_port: u16,
) -> Result<()> {
    let path = data_dir
        .join("traefik")
        .join("dynamic")
        .join(format!("tcp-{service_id}-{public_port}.yml"));
    if path.exists() {
        std::fs::remove_file(path)?;
    }
    Ok(())
}

/// Regenerate Traefik static config with additional TCP entryPoints.
/// Reads all TCP ports from dynamic configs and adds them as entryPoints.
pub fn regenerate_static_config_with_tcp(
    data_dir: &Path,
    acme_email: &str,
    dashboard: bool,
    tcp_ports: &[u16],
) -> Result<()> {
    let mut tcp_entries = String::new();
    for port in tcp_ports {
        tcp_entries.push_str(&format!("  tcp-{port}:\n    address: \":{port}\"\n"));
    }

    let dashboard_section = if dashboard {
        "api:\n  dashboard: true\n  insecure: true"
    } else {
        "api:\n  dashboard: false"
    };

    let config = format!(
        r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
{tcp_entries}
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
    );

    let traefik_dir = data_dir.join("traefik");
    std::fs::create_dir_all(&traefik_dir)?;
    std::fs::write(traefik_dir.join("traefik.yml"), config)?;
    Ok(())
}

/// Read TCP port numbers from traefik.yml entryPoints (tcp-NNNN entries).
#[allow(dead_code)]
pub fn read_tcp_ports_from_config(data_dir: &Path) -> Vec<u16> {
    let config_path = data_dir.join("traefik").join("traefik.yml");
    let content = match std::fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };
    let mut ports = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        // Match lines like "tcp-5432:" under entryPoints
        if let Some(rest) = trimmed.strip_prefix("tcp-") {
            if let Some(port_str) = rest.strip_suffix(':') {
                if let Ok(port) = port_str.parse::<u16>() {
                    ports.push(port);
                }
            }
        }
    }
    ports
}

/// Detect the public IP of this server.
pub async fn detect_public_ip() -> Result<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()?;

    // Try multiple services
    for url in &[
        "https://api.ipify.org",
        "https://ifconfig.me/ip",
        "https://icanhazip.com",
    ] {
        match client.get(*url).send().await {
            Ok(resp) => {
                if let Ok(ip) = resp.text().await {
                    let ip = ip.trim().to_string();
                    if !ip.is_empty() && ip.len() < 46 {
                        return Ok(ip);
                    }
                }
            }
            Err(_) => continue,
        }
    }

    Err(anyhow::anyhow!("Could not detect public IP"))
}
