use std::path::Path;

use anyhow::Result;

/// Generate Traefik static configuration (traefik.yml).
pub fn generate_static_config(acme_email: &str, dashboard: bool) -> String {
    let dashboard_section = if dashboard {
        "api:\n  dashboard: true\n  insecure: true"
    } else {
        "api:\n  dashboard: false"
    };

    format!(
        r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
    )
}

/// Generate Traefik dynamic config for a single domain → service mapping.
///
/// `service_id`: unique key for the router/service name
/// `domain`: the FQDN to route (e.g. "app.example.com")
/// `target_url`: upstream URL (e.g. "http://127.0.0.1:10042")
/// `use_tls`: whether to enable Let's Encrypt TLS
#[allow(dead_code)]
pub fn generate_dynamic_config(
    service_id: &str,
    domain: &str,
    target_url: &str,
    use_tls: bool,
) -> String {
    let tls_section = if use_tls {
        r#"      tls:
        certResolver: letsencrypt"#
            .to_string()
    } else {
        String::new()
    };

    // Parse domain: may contain path prefix (e.g., "api.voxly.one/v1")
    let (hostname, path_prefix) = if let Some(slash) = domain.find('/') {
        (&domain[..slash], Some(&domain[slash..]))
    } else {
        (domain, None)
    };
    let (rule, middleware_section, middleware_ref) = if let Some(path) = path_prefix {
        let mw_name = format!("strip-pier-{service_id}");
        (
            format!("Host(`{hostname}`) && PathPrefix(`{path}`)"),
            format!(
                r#"  middlewares:
    {mw_name}:
      stripPrefix:
        prefixes:
          - "{path}"
"#
            ),
            format!("\n      middlewares:\n        - {mw_name}"),
        )
    } else {
        (format!("Host(`{hostname}`)"), String::new(), String::new())
    };

    format!(
        r#"# Auto-generated by Pier for service {service_id}
http:
  routers:
    pier-{service_id}:
      rule: "{rule}"
      entryPoints:
        - websecure
{tls_section}{middleware_ref}
      service: pier-{service_id}
{middleware_section}  services:
    pier-{service_id}:
      loadBalancer:
        servers:
          - url: "{target_url}"
"#
    )
}

/// Write the Traefik static config to disk.
pub fn write_static_config(data_dir: &Path, acme_email: &str, dashboard: bool) -> Result<()> {
    let traefik_dir = data_dir.join("traefik");
    std::fs::create_dir_all(&traefik_dir)?;
    std::fs::create_dir_all(traefik_dir.join("dynamic"))?;

    // Preserve existing TCP entryPoints from current config
    let existing_tcp_ports = read_tcp_ports_from_config(data_dir);
    let config = if existing_tcp_ports.is_empty() {
        generate_static_config(acme_email, dashboard)
    } else {
        // Use regenerate_static_config_with_tcp to keep TCP ports
        let mut tcp_entries = String::new();
        for port in &existing_tcp_ports {
            tcp_entries.push_str(&format!("  tcp-{port}:\n    address: \":{port}\"\n"));
        }
        let dashboard_section = if dashboard {
            "api:\n  dashboard: true\n  insecure: true"
        } else {
            "api:\n  dashboard: false"
        };
        let cfg = format!(
            r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
{tcp_entries}
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
        );
        cfg
    };
    std::fs::write(traefik_dir.join("traefik.yml"), config)?;

    // Ensure acme.json exists with correct permissions (600 required by Traefik)
    let acme_path = traefik_dir.join("acme.json");
    if !acme_path.exists() {
        std::fs::write(&acme_path, "{}")?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&acme_path, std::fs::Permissions::from_mode(0o600))?;
    }

    Ok(())
}

/// Write a dynamic config file for a domain.
#[allow(dead_code)]
pub fn write_domain_config(
    data_dir: &Path,
    service_id: &str,
    domain: &str,
    target_url: &str,
    use_tls: bool,
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let config = generate_dynamic_config(service_id, domain, target_url, use_tls);
    let file_name = format!("{service_id}.yml");
    std::fs::write(dynamic_dir.join(file_name), config)?;

    Ok(())
}

/// Remove a dynamic config file for a service.
#[allow(dead_code)]
pub fn remove_domain_config(data_dir: &Path, service_id: &str) -> Result<()> {
    let file_path = data_dir
        .join("traefik")
        .join("dynamic")
        .join(format!("{service_id}.yml"));
    if file_path.exists() {
        std::fs::remove_file(file_path)?;
    }
    Ok(())
}

/// Generate a service domain using sslip.io (like Coolify).
/// Format: {name}-{short_id}.{ip}.sslip.io
pub fn generate_service_domain(service_name: &str, service_id: &str, server_ip: &str) -> String {
    // Clean name: lowercase, replace non-alphanumeric with dash
    let clean_name: String = service_name
        .to_lowercase()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    let clean_name = clean_name.trim_matches('-');

    // Take first 8 chars of service_id for short id
    let short_id = &service_id[..service_id.len().min(8)];

    format!("{clean_name}-{short_id}.{server_ip}.sslip.io")
}

/// One upstream endpoint behind the Traefik load balancer.
#[derive(Debug, Clone)]
pub struct LbUpstream {
    pub url: String,
    /// Relative weight. Only emitted when strategy == `Weighted`.
    pub weight: u32,
}

/// L7 load-balancing strategy for a service's upstreams.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LbStrategy {
    RoundRobin,
    Weighted,
    Sticky,
}

/// Extra load-balancer knobs (strategy + sticky cookie).
#[derive(Debug, Clone)]
pub struct LbConfig {
    pub strategy: LbStrategy,
    /// Cookie name used when `strategy == Sticky`. Ignored otherwise.
    pub sticky_cookie: Option<String>,
}

impl Default for LbConfig {
    fn default() -> Self {
        Self {
            strategy: LbStrategy::RoundRobin,
            sticky_cookie: None,
        }
    }
}

/// Generate Traefik dynamic config for a service with multiple domains and
/// multiple upstreams (replicas). When `upstreams.len() == 1` and strategy is
/// `RoundRobin`, the output matches legacy single-upstream YAML byte-for-byte.
pub fn generate_dynamic_config_lb(
    service_id: &str,
    domains: &[(String, bool)],
    upstreams: &[LbUpstream],
    lb: &LbConfig,
) -> String {
    let mut routers = String::new();
    let mut middlewares = String::new();
    for (i, (domain_with_path, use_tls)) in domains.iter().enumerate() {
        let router_name = if i == 0 {
            format!("pier-{service_id}")
        } else {
            format!("pier-{service_id}-{i}")
        };
        let tls_section = if *use_tls {
            "\n      tls:\n        certResolver: letsencrypt".to_string()
        } else {
            String::new()
        };
        let (hostname, path_prefix) = if let Some(slash) = domain_with_path.find('/') {
            (&domain_with_path[..slash], Some(&domain_with_path[slash..]))
        } else {
            (domain_with_path.as_str(), None)
        };
        let (rule, middleware_ref) = if let Some(path) = path_prefix {
            let mw_name = format!("strip-{router_name}");
            middlewares.push_str(&format!(
                r#"    {mw_name}:
      stripPrefix:
        prefixes:
          - "{path}"
"#
            ));
            (
                format!("Host(`{hostname}`) && PathPrefix(`{path}`)"),
                format!("\n      middlewares:\n        - {mw_name}"),
            )
        } else {
            (format!("Host(`{hostname}`)"), String::new())
        };
        routers.push_str(&format!(
            r#"    {router_name}:
      rule: "{rule}"
      entryPoints:
        - websecure{tls_section}{middleware_ref}
      service: pier-{service_id}
"#
        ));
    }

    let mw_section = if middlewares.is_empty() {
        String::new()
    } else {
        format!("  middlewares:\n{middlewares}")
    };

    let sticky_section = match (&lb.strategy, &lb.sticky_cookie) {
        (LbStrategy::Sticky, Some(cookie)) => format!(
            r#"        sticky:
          cookie:
            name: {cookie}
            httpOnly: true
            secure: true
"#
        ),
        _ => String::new(),
    };

    let include_weight = lb.strategy == LbStrategy::Weighted;
    let mut servers_yaml = String::new();
    for up in upstreams {
        if include_weight {
            servers_yaml.push_str(&format!(
                "          - url: \"{}\"\n            weight: {}\n",
                up.url, up.weight
            ));
        } else {
            servers_yaml.push_str(&format!("          - url: \"{}\"\n", up.url));
        }
    }

    format!(
        r#"# Auto-generated by Pier for service {service_id}
http:
  routers:
{routers}{mw_section}  services:
    pier-{service_id}:
      loadBalancer:
{sticky_section}        servers:
{servers_yaml}"#
    )
}

/// Legacy wrapper — single upstream, round-robin, no sticky.
#[allow(dead_code)]
pub fn generate_dynamic_config_multi(
    service_id: &str,
    domains: &[(String, bool)],
    target_url: &str,
) -> String {
    generate_dynamic_config_lb(
        service_id,
        domains,
        &[LbUpstream {
            url: target_url.to_string(),
            weight: 1,
        }],
        &LbConfig::default(),
    )
}

/// Regenerate Traefik config for a service with ALL its domains.
/// If no domains remain, removes the config file.
pub fn regenerate_service_config(
    data_dir: &Path,
    service_id: &str,
    domains: &[(String, bool)],
    target_url: &str,
) -> Result<()> {
    regenerate_service_config_lb(
        data_dir,
        service_id,
        domains,
        &[LbUpstream {
            url: target_url.to_string(),
            weight: 1,
        }],
        &LbConfig::default(),
    )
}

/// Regenerate Traefik config with an arbitrary upstream list + LB config.
pub fn regenerate_service_config_lb(
    data_dir: &Path,
    service_id: &str,
    domains: &[(String, bool)],
    upstreams: &[LbUpstream],
    lb: &LbConfig,
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;
    let file_path = dynamic_dir.join(format!("{service_id}.yml"));

    if domains.is_empty() || upstreams.is_empty() {
        if file_path.exists() {
            std::fs::remove_file(file_path)?;
        }
        return Ok(());
    }

    let config = generate_dynamic_config_lb(service_id, domains, upstreams, lb);
    if let Ok(existing) = std::fs::read_to_string(&file_path) {
        if existing == config {
            return Ok(());
        }
    }
    std::fs::write(file_path, config)?;
    Ok(())
}

/// Write Traefik config for the Pier platform domain.
pub fn write_platform_domain_config(data_dir: &Path, domain: &str, target_url: &str) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let config = format!(
        r#"# Pier platform domain
http:
  routers:
    pier-platform:
      rule: "Host(`{domain}`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: pier-platform
  services:
    pier-platform:
      loadBalancer:
        servers:
          - url: "{target_url}"
"#
    );
    std::fs::write(dynamic_dir.join("_pier-platform.yml"), config)?;
    Ok(())
}

/// Remove the platform domain config.
pub fn remove_platform_domain_config(data_dir: &Path) -> Result<()> {
    let path = data_dir
        .join("traefik")
        .join("dynamic")
        .join("_pier-platform.yml");
    if path.exists() {
        std::fs::remove_file(path)?;
    }
    Ok(())
}

/// Write a Traefik TCP dynamic config for exposing a service port publicly.
/// Creates `tcp-{service_id}.yml` in the dynamic config directory.
pub fn write_tcp_route(
    data_dir: &Path,
    service_id: &str,
    public_port: u16,
    container_name: &str,
    container_port: u16,
) -> Result<()> {
    let dynamic_dir = data_dir.join("traefik").join("dynamic");
    std::fs::create_dir_all(&dynamic_dir)?;

    let ep_name = format!("tcp-{public_port}");
    let config = format!(
        r#"# TCP proxy for service {service_id} (port {public_port} -> {container_name}:{container_port})
tcp:
  routers:
    tcp-{service_id}:
      entryPoints:
        - "{ep_name}"
      rule: "HostSNI(`*`)"
      service: "tcp-{service_id}"
  services:
    tcp-{service_id}:
      loadBalancer:
        servers:
          - address: "{container_name}:{container_port}"
"#
    );

    std::fs::write(
        dynamic_dir.join(format!("tcp-{service_id}.yml")),
        config,
    )?;
    Ok(())
}

/// Remove a TCP route config for a service.
pub fn remove_tcp_route(data_dir: &Path, service_id: &str) -> Result<()> {
    let path = data_dir
        .join("traefik")
        .join("dynamic")
        .join(format!("tcp-{service_id}.yml"));
    if path.exists() {
        std::fs::remove_file(path)?;
    }
    Ok(())
}

/// Regenerate Traefik static config with additional TCP entryPoints.
/// Reads all TCP ports from dynamic configs and adds them as entryPoints.
pub fn regenerate_static_config_with_tcp(
    data_dir: &Path,
    acme_email: &str,
    dashboard: bool,
    tcp_ports: &[u16],
) -> Result<()> {
    let mut tcp_entries = String::new();
    for port in tcp_ports {
        tcp_entries.push_str(&format!(
            "  tcp-{port}:\n    address: \":{port}\"\n"
        ));
    }

    let dashboard_section = if dashboard {
        "api:\n  dashboard: true\n  insecure: true"
    } else {
        "api:\n  dashboard: false"
    };

    let config = format!(
        r#"# Pier-managed Traefik configuration — do not edit manually
{dashboard_section}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
{tcp_entries}
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{acme_email}"
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /data/traefik/dynamic
    watch: true

log:
  level: WARN
"#
    );

    let traefik_dir = data_dir.join("traefik");
    std::fs::create_dir_all(&traefik_dir)?;
    std::fs::write(traefik_dir.join("traefik.yml"), config)?;
    Ok(())
}

/// Read TCP port numbers from traefik.yml entryPoints (tcp-NNNN entries).
#[allow(dead_code)]
pub fn read_tcp_ports_from_config(data_dir: &Path) -> Vec<u16> {
    let config_path = data_dir.join("traefik").join("traefik.yml");
    let content = match std::fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };
    let mut ports = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        // Match lines like "tcp-5432:" under entryPoints
        if let Some(rest) = trimmed.strip_prefix("tcp-") {
            if let Some(port_str) = rest.strip_suffix(':') {
                if let Ok(port) = port_str.parse::<u16>() {
                    ports.push(port);
                }
            }
        }
    }
    ports
}

/// Detect the public IP of this server.
pub async fn detect_public_ip() -> Result<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()?;

    // Try multiple services
    for url in &[
        "https://api.ipify.org",
        "https://ifconfig.me/ip",
        "https://icanhazip.com",
    ] {
        match client.get(*url).send().await {
            Ok(resp) => {
                if let Ok(ip) = resp.text().await {
                    let ip = ip.trim().to_string();
                    if !ip.is_empty() && ip.len() < 46 {
                        return Ok(ip);
                    }
                }
            }
            Err(_) => continue,
        }
    }

    Err(anyhow::anyhow!("Could not detect public IP"))
}
