//! Standalone retrofit installer scripts served by pier-core.
//!
//! The agent-installer rendered by [`super::servers::install_script`]
//! is for *fresh* nodes that need pier-agent + handshake + the helper
//! bundled in one go. This module hosts the smaller, retrofit-only
//! variants:
//!
//! * `GET /install-helper.sh` — installs `pier-net-helper` on a node
//!   that already runs pier-agent (or pier-core) but has no helper
//!   yet, e.g. an existing peer registered before Etap 0.2 shipped.
//!   Does NOT touch pier-agent.service or do a handshake.
//!
//! These endpoints are public on purpose — they're meant to be fetched
//! via `curl | bash` from a fresh-ish VPS that has no Pier credential
//! yet. Authorization is "you know the core's URL", which is the same
//! property `install_script` already relies on.

use axum::extract::State;
use axum::http::{header, StatusCode};
use axum::response::{IntoResponse, Response};

use crate::state::SharedState;

/// `GET /install-helper.sh`
///
/// Renders a self-contained shell script that downloads the
/// `pier-net-helper` binary, drops the same systemd unit
/// [`servers::install_script`] emits for fresh installs, and enables
/// the service. Idempotent — re-running on a node that already has
/// the helper just restarts the unit.
pub async fn install_helper_script(State(state): State<SharedState>) -> Response {
    let server_ip = {
        let db = match state.db.lock() {
            Ok(d) => d,
            Err(_) => {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "DB lock poisoned",
                )
                    .into_response()
            }
        };
        db.query_row(
            "SELECT value FROM settings WHERE key = 'server.public_ip'",
            [],
            |row| row.get::<_, String>(0),
        )
        .unwrap_or_else(|_| "YOUR_PIER_SERVER_IP".to_string())
    };
    let pier_port = state.config.port;
    let tls_enabled = state.config.tls_mode != crate::config::TlsMode::Off;
    let scheme = if tls_enabled { "https" } else { "http" };
    // IPv6 literals need brackets in URL authority — the helper
    // tolerates v4 / hostnames unchanged.
    let server_authority =
        crate::network::address::authority(&server_ip, pier_port.into());

    // Note: we don't bundle pier-core's self-signed cert here. The
    // helper download URL points at the public GitHub release, not at
    // core, so curl's normal CA verification works. The optional
    // post-install `curl $PIER_CORE_URL/api/v1/health` uses `--insecure`
    // since it's purely diagnostic.
    let script = format!(
        r#"#!/bin/bash
set -euo pipefail

# Pier Network Helper Retrofit Installer
# Auto-generated by Pier core
#
# Drop-in installer for `pier-net-helper` — the privileged root daemon
# that pier-agent or pier-core uses to bring up a WireGuard mesh.
#
# Run this on a node that ALREADY has pier-agent (or pier-core)
# installed but is missing the helper, e.g. peers registered before
# Etap 0.2. For brand-new nodes, use the bundled install.sh instead.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (it installs a systemd unit)." >&2
    exit 1
fi

PIER_CORE_URL="{scheme}://{server_authority}"
HELPER_URL="https://github.com/joveptesg/Pier/releases/download/latest/pier-net-helper-linux-amd64"

echo "=== Pier Network Helper Retrofit ==="
echo "Core server:   $PIER_CORE_URL"
echo "Download URL:  $HELPER_URL"

# Sanity-ping the core. Use --insecure because the operator's
# self-signed cert isn't in this machine's trust store; we only use
# this call for a "yes, the URL is reachable" smoke check.
if ! curl -fsSL --insecure --max-time 5 "$PIER_CORE_URL/api/v1/health" >/dev/null; then
    echo "Warning: $PIER_CORE_URL/api/v1/health is unreachable. Continuing anyway — the helper itself doesn't talk to core."
fi

# 1. Binary
echo "Downloading pier-net-helper..."
curl -fsSL -o /usr/local/bin/pier-net-helper "$HELPER_URL" || {{
    echo "Error: could not download pier-net-helper from $HELPER_URL" >&2
    echo "If your platform isn't linux-amd64, build from source:" >&2
    echo "  cargo build --release -p pier-net-helper" >&2
    echo "  install -m 0755 target/release/pier-net-helper /usr/local/bin/" >&2
    exit 1
}}
chmod 0755 /usr/local/bin/pier-net-helper

# 2. systemd unit — mirrors the inline definition that fresh install.sh
#    emits for new agents. Kept in sync intentionally; if you change one,
#    change the other in crates/pier-core/src/api/servers.rs.
echo "Installing systemd unit..."
cat > /etc/systemd/system/pier-net-helper.service <<'HELPER_UNIT'
[Unit]
Description=Pier Network Helper (privileged WireGuard mesh operations)
Documentation=https://github.com/joveptesg/Pier
After=network-pre.target
Before=pier-agent.service

[Service]
Type=simple
ExecStart=/usr/local/bin/pier-net-helper
Restart=on-failure
RestartSec=2
User=root
Group=root
RuntimeDirectory=pier
RuntimeDirectoryMode=0750
ProtectSystem=strict
ReadWritePaths=/etc/wireguard /run/pier
ProtectHome=true
PrivateTmp=true
NoNewPrivileges=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictNamespaces=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
AmbientCapabilities=CAP_NET_ADMIN CAP_SYS_MODULE
CapabilityBoundingSet=CAP_NET_ADMIN CAP_SYS_MODULE

[Install]
WantedBy=multi-user.target
HELPER_UNIT
chmod 644 /etc/systemd/system/pier-net-helper.service

# 3. Enable + start (idempotent — re-running just restarts).
systemctl daemon-reload
systemctl enable --now pier-net-helper.service

# 4. Smoke check — the socket should exist after start. Retry briefly to
#    let the daemon settle; if it never shows, surface the unit's last
#    few journal lines so the operator can debug.
for i in 1 2 3 4 5; do
    if [ -S /run/pier/net.sock ]; then
        echo "Helper online: /run/pier/net.sock present."
        echo "Done. The Pier UI's mesh preflight should now report this node green."
        exit 0
    fi
    sleep 1
done

echo "Warning: /run/pier/net.sock did not appear after 5s. Recent journal:" >&2
journalctl -u pier-net-helper.service --no-pager --lines=20 || true
exit 1
"#
    );

    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "text/x-shellscript; charset=utf-8"),
            (
                header::CONTENT_DISPOSITION,
                "inline; filename=\"install-helper.sh\"",
            ),
        ],
        script,
    )
        .into_response()
}
