//! Standalone retrofit installer scripts served by pier-core.
//!
//! The agent-installer rendered by [`super::servers::install_script`]
//! is for *fresh* nodes that need pier-agent + handshake + the helper
//! bundled in one go. This module hosts the smaller, retrofit-only
//! variants:
//!
//! * `GET /install-helper.sh` — installs `pier-net-helper` on a node
//!   that already runs pier-agent (or pier-core) but has no helper
//!   yet, e.g. an existing peer registered before Etap 0.2 shipped.
//!   Does NOT touch pier-agent.service or do a handshake.
//!
//! These endpoints are public on purpose — they're meant to be fetched
//! via `curl | bash` from a fresh-ish VPS that has no Pier credential
//! yet. Authorization is "you know the core's URL", which is the same
//! property `install_script` already relies on.

use axum::extract::State;
use axum::http::{header, StatusCode};
use axum::response::{IntoResponse, Response};

use crate::state::SharedState;

/// `GET /install-helper.sh`
///
/// Renders a self-contained shell script that downloads the
/// `pier-net-helper` binary, drops the canonical systemd unit
/// ([`crate::network::helper_unit::HELPER_UNIT`] — literally the same
/// bytes `install.sh` and the agent bootstrap write), and enables the
/// service. Idempotent — re-running on a node that already has the
/// helper just restarts the unit.
pub async fn install_helper_script(State(state): State<SharedState>) -> Response {
    let server_ip = {
        let db = match state.db.lock() {
            Ok(d) => d,
            Err(_) => {
                return (StatusCode::INTERNAL_SERVER_ERROR, "DB lock poisoned").into_response()
            }
        };
        db.query_row(
            "SELECT value FROM settings WHERE key = 'server.public_ip'",
            [],
            |row| row.get::<_, String>(0),
        )
        .unwrap_or_else(|_| "YOUR_PIER_SERVER_IP".to_string())
    };
    let pier_port = state.config.port;
    let tls_enabled = state.config.tls_mode != crate::config::TlsMode::Off;
    let scheme = if tls_enabled { "https" } else { "http" };
    // IPv6 literals need brackets in URL authority — the helper
    // tolerates v4 / hostnames unchanged.
    let server_authority = crate::network::address::authority(&server_ip, pier_port.into());

    // The unit body + `groupadd pier` guard, rendered from the one copy in
    // scripts/pier-net-helper.service. Never inline a second copy here.
    let helper_unit_sh = crate::network::helper_unit::install_unit_sh();

    // Note: we don't bundle pier-core's self-signed cert here. The
    // helper download URL points at the public GitHub release, not at
    // core, so curl's normal CA verification works. The optional
    // post-install `curl $PIER_CORE_URL/api/v1/health` uses `--insecure`
    // since it's purely diagnostic.
    let script = format!(
        r#"#!/bin/bash
set -euo pipefail

# Pier Network Helper Retrofit Installer
# Auto-generated by Pier core
#
# Drop-in installer for `pier-net-helper` — the privileged root daemon
# that pier-agent or pier-core uses to bring up a WireGuard mesh.
#
# Run this on a node that ALREADY has pier-agent (or pier-core)
# installed but is missing the helper, e.g. peers registered before
# Etap 0.2. For brand-new nodes, use the bundled install.sh instead.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (it installs a systemd unit)." >&2
    exit 1
fi

PIER_CORE_URL="{scheme}://{server_authority}"
HELPER_URL="https://github.com/joveptesg/pier/releases/download/latest/pier-net-helper-linux-amd64"

echo "=== Pier Network Helper Retrofit ==="
echo "Core server:   $PIER_CORE_URL"
echo "Download URL:  $HELPER_URL"

# Sanity-ping the core. Use --insecure because the operator's
# self-signed cert isn't in this machine's trust store; we only use
# this call for a "yes, the URL is reachable" smoke check.
if ! curl -fsSL --insecure --max-time 5 "$PIER_CORE_URL/api/v1/health" >/dev/null; then
    echo "Warning: $PIER_CORE_URL/api/v1/health is unreachable. Continuing anyway — the helper itself doesn't talk to core."
fi

# 1. Binary
#    Download beside the target and rename into place. Writing directly over
#    /usr/local/bin/pier-net-helper fails with ETXTBSY whenever the helper is
#    already running — and re-running this installer on a node that has the
#    helper is precisely the documented remedy for a bad socket. rename(2)
#    swaps the inode instead, which the kernel allows on a running binary.
echo "Downloading pier-net-helper..."
curl -fsSL -o /usr/local/bin/pier-net-helper.new "$HELPER_URL" || {{
    echo "Error: could not download pier-net-helper from $HELPER_URL" >&2
    echo "If your platform isn't linux-amd64, build from source:" >&2
    echo "  cargo build --release -p pier-net-helper" >&2
    echo "  install -m 0755 target/release/pier-net-helper /usr/local/bin/" >&2
    rm -f /usr/local/bin/pier-net-helper.new
    exit 1
}}
chmod 0755 /usr/local/bin/pier-net-helper.new
mv -f /usr/local/bin/pier-net-helper.new /usr/local/bin/pier-net-helper

# 2. systemd unit — emitted verbatim from scripts/pier-net-helper.service,
#    the single source of truth shared with install.sh and the agent
#    bootstrap (crates/pier-core/src/network/helper_unit.rs).
echo "Installing systemd unit..."
{helper_unit_sh}
# 3. Enable + start (idempotent — re-running just restarts).
systemctl daemon-reload
systemctl enable --now pier-net-helper.service

# 4. Smoke check. Socket EXISTENCE is not enough: issue #9 was a socket
#    that existed but was root:root, which every "is it there?" check
#    reported green while pier-core got EACCES on connect(). So assert the
#    group, and — when a pier user exists — actually connect as it.
for i in 1 2 3 4 5; do
    [ -S /run/pier/net.sock ] && break
    sleep 1
done

if [ ! -S /run/pier/net.sock ]; then
    echo "Error: /run/pier/net.sock did not appear after 5s. Recent journal:" >&2
    journalctl -u pier-net-helper.service --no-pager --lines=20 >&2 || true
    exit 1
fi

SOCK_OWNER=$(stat -c '%U:%G' /run/pier/net.sock)
if [ "$SOCK_OWNER" != "root:pier" ]; then
    echo "Error: /run/pier/net.sock is $SOCK_OWNER, expected root:pier." >&2
    echo "pier-core runs as the unprivileged pier user and will get EACCES on connect()." >&2
    echo "Check Group=pier in /etc/systemd/system/pier-net-helper.service." >&2
    journalctl -u pier-net-helper.service --no-pager --lines=20 >&2 || true
    exit 1
fi

if id pier >/dev/null 2>&1; then
    if ! su -s /bin/sh -c 'test -r /run/pier/net.sock && test -w /run/pier/net.sock' pier; then
        echo "Error: user 'pier' cannot read/write /run/pier/net.sock ($SOCK_OWNER)." >&2
        echo "Is pier a member of the pier group? Run: id pier" >&2
        exit 1
    fi
fi

echo "Helper online: /run/pier/net.sock ($SOCK_OWNER, reachable by pier)."
echo "Done. The Pier UI's mesh preflight should now report this node green."
exit 0
"#
    );

    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "text/x-shellscript; charset=utf-8"),
            (
                header::CONTENT_DISPOSITION,
                "inline; filename=\"install-helper.sh\"",
            ),
        ],
        script,
    )
        .into_response()
}
